name: ci

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  lint:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install ruff

      - name: Ruff lint
        run: ruff check .

      - name: Ruff format check
        run: ruff format . --check
